---
- name: Run Backend API
  community.docker.docker_container:
    name: backend-api
    image: "{{ image_name | default('gorgorq/simple-api') }}:{{ image_tag | default('1.0') }}"
    state: started
    recreate: yes
    restart_policy: on-failure
    restart_retries: 3
    networks:
      - name: backend-network
      - name: proxy-network
    env:
      POSTGRES_HOST: "{{ backend_api_host }}"
      POSTGRES_PORT: "{{ backend_api_port | string }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"

