---
- name: Run Backend API
  community.docker.docker_container:
    name: backend-api
    image: gorgorq/simple-api:1.0
    restart_policy: on-failure:3
    networks:
      - name: internal-network
      - name: app-network
    env:
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
  
