services:
    backend-api:
        build: ../Backend API
        env_file:
            - ../.env
        environment:
            - POSTGRES_HOST=database
        networks:
            - app-network
        depends_on:
            database:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    database:
        build: ../Database
        env_file:
            - ../.env
        networks:
            - app-network
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U usr -d db"]
            interval: 10s
            timeout: 5s
            retries: 5

    httpd:
        build: ../Http server
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            backend-api:
                condition: service_healthy

networks:
    app-network:

volumes:
    postgres-data:
