---
- name: Create frontend directory
  file:
    path: /opt/frontend
    state: directory
    mode: '0755'

- name: Copy frontend built files
  copy:
    src: "{{ playbook_dir }}/../../front-end/dist/"
    dest: /opt/frontend/
    mode: '0644'

- name: Run HTTPD reverse proxy
  community.docker.docker_container:
    name: httpd
    image: "{{ httpd_image_name | default('gorgorq/my-httpd') }}:{{ httpd_image_tag | default('1.0') }}"
    state: started
    restart_policy: no
    networks:
      - name: proxy-network
    ports:
      - "80:80"
    volumes:
      - /opt/frontend:/usr/local/apache2/htdocs:ro
    env:
      BACKEND_API_HOST: "{{ backend_api_host }}"
      BACKEND_API_PORT: "{{ backend_api_port | string }}"
