---
- name: Create frontend directory
  file:
    path: /opt/frontend
    mode: '0755'

- name: Run HTTPD reverse proxy
  community.docker.docker_container:
    name: httpd
    image: "{{ httpd_image_name | default('gorgorq/my-httpd') }}:{{ httpd_image_tag | default('1.0') }}"
    state: started
    recreate: yes
    restart_policy: no
    pull: true  
    networks:
      - name: proxy-network
    ports:
      - "80:80"
    env:
      BACKEND_API_HOST: "{{ backend_api_host | default('backend-api') }}"
      BACKEND_API_PORT: "{{ backend_api_port | default('8080') | string }}"
