---
- name: Run HTTPD reverse proxy
  community.docker.docker_container:
    name: httpd
    image: gorgorq/my-httpd:1.0
    state: started
    restart_policy: no
    networks:
      - name: app-network
    ports:
      - "80:80"
    env:
      BACKEND_API_HOST: "{{ backend_api_host }}"
      BACKEND_API_PORT: "{{ backend_api_port }}"
