name: Build and Push Docker Images

# Trigger only when test workflow completes successfully on main branch
on:
  workflow_run:
    workflows: ["Test Backend"]  
    types:
      - completed
    branches:
      - main

jobs:
  # Job: Build and push Docker images (only if tests passed)
  build-and-push-docker-image:
    # Only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout code to access Dockerfiles
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Authenticate to Docker Hub using secured credentials
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        # Uses GitHub Secrets to securely store Docker Hub credentials

      # Step 3: Build and push backend API Docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./TP_1/Backend API  # Path to Dockerfile and application code
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: true  # Always push since we're only on main branch
        # This workflow only runs on main after successful tests

      # Step 4: Build and push PostgreSQL database Docker image
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./TP_1/Database  # Contains Dockerfile and SQL init scripts
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: true

      # Step 5: Build and push Apache HTTP server Docker image (reverse proxy)
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./TP_1/Http server  # Contains Dockerfile, httpd.conf, and index.html
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: true

# Workflow Configuration Summary:
# - This workflow is triggered by the completion of "Test Backend" workflow
# - Only runs on main branch
# - Only executes if test workflow concluded successfully
# - Builds and pushes all three Docker images to Docker Hub
# - Uses workflow_run trigger to ensure tests pass before deployment