name: sonarcloud-analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: |
          cd "TP_1/Backend API"
          mvn clean verify

      - name: Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd "TP_1/Backend API"
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=tp-docker_project-tp-docker \
            -Dsonar.organization=tp-docker \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.branch.name=main